apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gorovideo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.11
        ports:
        - containerPort: 80